// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkMCrYPHY35aje40dURy6lcDXnl5vndSQ',
    appId: '1:429531477012:android:2c9b372c0dbfc78ab7e301',
    messagingSenderId: '429531477012',
    projectId: 'career-paddy',
    databaseURL: 'https://career-paddy-default-rtdb.firebaseio.com',
    storageBucket: 'career-paddy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6qg2EaPbRsBco5hHOlvqkO89oqaE-d0s',
    appId: '1:429531477012:ios:3315047297156787b7e301',
    messagingSenderId: '429531477012',
    projectId: 'career-paddy',
    databaseURL: 'https://career-paddy-default-rtdb.firebaseio.com',
    storageBucket: 'career-paddy.appspot.com',
    androidClientId: '429531477012-nmh4pppjm0eor176k4bjktojcr978fko.apps.googleusercontent.com',
    iosClientId: '429531477012-p9mro9as236qe12hpdsetii16j4vpqqk.apps.googleusercontent.com',
    iosBundleId: 'com.careerpaddy.CareerPaddy',
  );
}
